export default new Map()
  .set('ikea', new Map()
    .set(1, { description: 'Unterbau Schränke, Schubladen und Spüle', price: 1700, link: 'https://www.ikea.com/de/de/cat/metod-einzelteile-23598/' })
  )
  .set('baumarkt', new Map()
    .set(1, { description: 'Pauschale für Holz, Schrauben, etc', price: 200, link: '' })
  )
  .set('arbeitsplatte', new Map()
    .set(1, { description: 'Eiche Leimholz Keilgezinkt', price: 567.17, link: 'https://www.leipziger-kistenfabrik.de/produkte/plattenwerkstoffe/leimholz/' })
    .set(2, { description: 'Nussbaum Leimholz Keilgezinkt', price: 848.10, link: 'https://www.leipziger-kistenfabrik.de/produkte/plattenwerkstoffe/leimholz/' })
    .set(3, { description: 'Esche Leimholz Keilgezinkt', price: 1045.65, link: 'https://www.leipziger-kistenfabrik.de/produkte/plattenwerkstoffe/leimholz/' })
    .set(4, { description: 'Ahorn Leimholz durchg. Lamelle', price: 1161.57, link: 'https://www.leipziger-kistenfabrik.de/produkte/plattenwerkstoffe/leimholz/' })
  )
  .set('blenden', new Map()
    .set(1, { description: 'Fichte Leimholz durchg. Lamelle 18mm', price: 75.13, link: 'https://www.leipziger-kistenfabrik.de/produkte/plattenwerkstoffe/leimholz/' })
    .set(2, { description: 'Birke-Multiplex 12mm', price: 83.64, link: 'https://www.leipziger-kistenfabrik.de/produkte/plattenwerkstoffe/sperrholz/multiplex-buche-und-birke/' })
  )
  .set('spuelmaschine', new Map()
    .set(1, { description: 'Gebraucht, möglichst langlebig und leise (hälfte vom haus)', price: 120, link: '' })
  )
  .set('herd', new Map()
    .set(1, { description: 'Zanussi, Induktion, touch, Kochfeldabzug, 80cm, Neu (hälfte vom haus)', price: 405, link: 'https://geizhals.de/zanussi-zifn844x-induktionskochfeld-mit-kochfeldabzug-autark-949-595-755-a3096611.html' })
    .set(2, { description: 'Küppersbusch, Induktion, kein touch, 80cm, Neu (hälfte vom haus)', price: 500, link: 'https://geizhals.de/kueppersbusch-k-series-8-ki8810-0sr-induktionskochfeld-autark-a2894395.html' })
    .set(3, { description: 'Elica Induktion, kein touch, Kochfeldabzug, 90cm, Gebraucht (hälfte vom haus)', price: 600, link: 'https://www.kleinanzeigen.de/s-anzeige/elica-nikolatesla-unplugged-prf0184019-induktion-kochfeldabzug/2964606636-176-697' })
    .set(4, { description: 'Elica Induktion, kein touch, Kochfeldabzug, 90cm, Neu (hälfte vom haus)', price: 1000, link: 'https://geizhals.de/elica-nikolatesla-unplugged-bl-f-90-induktionskochfeld-autark-mit-kochfeldabzug-prf0184019-a2950297.html' })
  )
  .set('dunstabzug', new Map()
    .set(1, { description: 'Keine', price: 0, link: '' })
    .set(2, { description: 'Irgendwas, hauptsache Umluft (hälfte vom haus)', price: 50, link: 'https://geizhals.de/?cat=hdunst&xf=4469_Umluft' })
  )
  .set('ofen', new Map()
    .set(1, { description: 'Gebraucht, möglichst langlebig (hälfte vom haus)', price: 150, link: '' })
  )
